name: Daily fetch and push to Supabase

on:
  schedule:
    - cron: '0 0 * * *' # Tous les jours à 00h UTC
  workflow_dispatch:    # Permet de le lancer manuellement via GitHub

jobs:
  fetch-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run fetch script
      env:
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: |
        python main.py